import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Loader2, Copy, Check, Sparkles, Download } from 'lucide-react';

export default function OutputPanel({ result, isLoading }) {
  const [copiedSection, setCopiedSection] = useState(null);
  const [displayedExplanation, setDisplayedExplanation] = useState("");
  const [visibleSections, setVisibleSections] = useState({
    explanation: false,
    sources: false,
    fix: false,
    why: false,
    opt: false
  });
  
  const typingTimerRef = useRef(null);
  const typingIndexRef = useRef(0);

  /**
   * Defensive rendering helper to remove broken strings
   */
  const safeClean = useCallback((text, fallback = "") => {
    if (text === undefined || text === null) return fallback;
    if (typeof text !== 'string') return String(text);

    const cleaned = text.trim();
    // Only treat entire placeholder payloads as empty; preserve meaningful words like "null".
    if (cleaned === "undefined" || cleaned === "null") {
      return fallback;
    }
    return cleaned || fallback;
  }, []);

  const normalizeNarrativeText = useCallback((text) => {
    // If text is null/undefined/object, safeClean handles it.
    const cleaned = safeClean(text);
    if (!cleaned || cleaned === "undefined") return "";
    
    // Core cleanup: just trim and fix spacing.
    // We trust the backend's core message.
    return cleaned.trim()
      .replace(/\s+/g, " ")
      .replace(/\.\.+/g, ".");
  }, [safeClean]);

  const handleCopy = (text, section) => {
    navigator.clipboard.writeText(safeClean(text));
    setCopiedSection(section);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleDownloadReport = () => {
    if (!result) return;
    
    const md = `# 🧠 AI Debug Report

## 📌 Error Type
${safeClean(result.error_type, "Logical Error")}

## 📊 Confidence
${result.confidence ? (result.confidence * 100).toFixed(0) + "%" : "Unknown"} - ${safeClean(result.confidence_reason, "Heuristic analysis")}

## 📝 Explanation
${safeClean(formatExplanation(result.explanation))}

## 🛠 Fixed Code
\`\`\`
${safeClean(result.fix, "// No fix generated")}
\`\`\`

## 💡 Why it works
${safeClean(result.why_fix_works, "Applied standard reliability improvements.")}

${result.optimized_code && result.optimized_code !== result.fix ? `
## 🚀 Optimized Version
\`\`\`
${safeClean(result.optimized_code)}
\`\`\`
` : ""}

---
*Generated by AI Debugging Assistant*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `debug_report_${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const formatExplanation = useCallback((text) => {
    const raw = safeClean(text);
    if (!raw) return "";
    
    // If the explanation itself is a JSON string (sometimes happens with models), try to parse.
    if (raw.startsWith('{')) {
      try {
        const parsed = JSON.parse(raw);
        return normalizeNarrativeText(parsed.explanation || parsed.message || raw);
      } catch {
        return normalizeNarrativeText(raw);
      }
    }
    return normalizeNarrativeText(raw);
  }, [safeClean, normalizeNarrativeText]);

  // Logic for Typing Effect & Sequential Reveal
  useEffect(() => {
    if (!result) {
      setVisibleSections({ explanation: false, sources: false, fix: false, why: false, opt: false });
      setDisplayedExplanation("");
      return;
    }

    const fullExp = formatExplanation(result.explanation);
    
    if (!fullExp || fullExp === "undefined") {
      setDisplayedExplanation("");
      revealNextSections();
      return;
    }

    if (result.isHistoryPreview || (result.warning && result.warning.includes("limit"))) {
      setDisplayedExplanation(fullExp);
      setVisibleSections({ explanation: true, sources: true, fix: true, why: true, opt: true });
      return;
    }

    // Reset Typing State
    setDisplayedExplanation("");
    typingIndexRef.current = 0;
    setVisibleSections({ explanation: true, sources: false, fix: false, why: false, opt: false });
    
    if (typingTimerRef.current) clearInterval(typingTimerRef.current);
    
    typingTimerRef.current = setInterval(() => {
      const idx = typingIndexRef.current;
      if (idx < fullExp.length) {
        const char = fullExp[idx];
        setDisplayedExplanation((prev) => prev + char);
        typingIndexRef.current = idx + 1;
      } else {
        clearInterval(typingTimerRef.current);
        revealNextSections();
      }
    }, 10);

    return () => {
      if (typingTimerRef.current) clearInterval(typingTimerRef.current);
    };
  }, [result, formatExplanation]);

  const revealNextSections = () => {
    const sequence = ['sources', 'fix', 'why', 'opt'];
    sequence.forEach((section, i) => {
      setTimeout(() => {
        setVisibleSections(prev => ({ ...prev, [section]: true }));
      }, (i + 1) * 300); 
    });
  };

  const CopyButton = ({ text, section }) => {
    const isCopied = copiedSection === section;
    const cleanContent = safeClean(text);
    return (
      <button
        onClick={() => handleCopy(cleanContent, section)}
        className="absolute top-2 right-2 p-1.5 text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-md transition-colors"
        title="Copy code"
      >
        {isCopied ? <Check size={14} className="text-green-600 dark:text-green-400" /> : <Copy size={14} />}
      </button>
    );
  };

  const Skeleton = ({ className }) => (
    <div className={`animate-pulse bg-gray-200 dark:bg-gray-800 rounded-lg ${className}`} />
  );

  if (isLoading) {
    return (
      <div className="flex flex-col gap-6">
        <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <Loader2 className="animate-spin text-blue-500" size={20} />
            <Skeleton className="h-6 w-32" />
          </div>
          <Skeleton className="h-4 w-full mb-2" />
          <Skeleton className="h-4 w-5/6 mb-2" />
          <Skeleton className="h-4 w-4/6" />
        </div>
        <div className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl p-6 shadow-sm">
          <Skeleton className="h-6 w-40 mb-4" />
          <Skeleton className="h-40 w-full" />
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="h-full min-h-[400px] flex flex-col items-center justify-center p-8 text-center bg-gray-50 dark:bg-gray-900/50 border border-dashed border-gray-300 dark:border-gray-800 rounded-xl">
        <Sparkles className="text-gray-300 dark:text-gray-700 mb-4" size={48} />
        <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">
          Ready to analyze. Paste your code and hit Debug!
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6">

      {visibleSections.explanation && (
        <div className="flex items-center justify-end">
          <button
            onClick={handleDownloadReport}
            className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-gray-600 dark:text-gray-300 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-all shadow-sm active:scale-95"
          >
            <Download size={16} />
            Download Summary
          </button>
        </div>
      )}

      {result.warning && (
        <div className="animate-in fade-in slide-in-from-top-4 duration-500 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800/50 rounded-xl p-4 flex items-start gap-3 shadow-sm">
          <p className="text-sm font-medium text-red-800 dark:text-red-200">
            ⚠️ {result.warning.includes("limit") ? "API limit reached. Please try again later." : result.warning}
          </p>
        </div>
      )}

      {visibleSections.explanation && (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-200">Explanation</h3>
              <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-700 border border-blue-200 dark:bg-blue-900/30 dark:text-blue-300 dark:border-blue-800">
                {safeClean(result.error_type, result.isExplain ? "Explain Mode" : "Logical Error")}
              </span>
              {result.confidence !== undefined && (
                <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-bold border shadow-sm ${
                  result.confidence >= 0.85 ? 'bg-green-100 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-400 dark:border-green-800' :
                  result.confidence >= 0.6 ? 'bg-yellow-100 text-yellow-700 border-yellow-200 dark:bg-yellow-900/30 dark:text-yellow-400 dark:border-yellow-800' :
                  'bg-red-100 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-400 dark:border-red-800'
                }`}>
                  {Math.round(result.confidence * 100)}% Match
                </span>
              )}
            </div>
          </div>
          <p className="text-gray-700 dark:text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">
            {safeClean(displayedExplanation)}
            {displayedExplanation.length < formatExplanation(result.explanation).length && (
              <span className="inline-block w-1 h-4 bg-blue-500 ml-1 animate-pulse align-middle" />
            )}
          </p>
        </div>
      )}

      {visibleSections.sources && result.sources && result.sources.length > 0 && (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl p-6 shadow-sm">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-200 mb-4">Source Context</h3>
          <div className="bg-gray-50 dark:bg-gray-950 border border-gray-200 dark:border-gray-800 rounded-lg p-4">
            <ul className="list-disc pl-5 space-y-2 text-sm text-gray-700 dark:text-gray-300">
              {result.sources.slice(0, 3).map((source, index) => (
                <li key={index} className="leading-relaxed">
                  {safeClean(source).length > 150 ? safeClean(source).substring(0, 150).trim() + "..." : safeClean(source)}
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {visibleSections.fix && result.fix && (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl p-6 shadow-sm">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-200 mb-4">Fixed Code</h3>
          <div className="relative group bg-gray-50 dark:bg-gray-950 border border-gray-200 dark:border-gray-800 rounded-lg">
            <CopyButton text={result.fix} section="fix" />
            <div className="p-4 overflow-x-auto">
              <pre className="text-sm font-mono text-gray-900 dark:text-gray-200 whitespace-pre-wrap break-words pr-8">{safeClean(result.fix)}</pre>
            </div>
          </div>
        </div>
      )}

      {visibleSections.why && result.why_fix_works && (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl p-6 shadow-sm">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-200 mb-4">Why this fix works</h3>
          <p className="text-gray-700 dark:text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">
            {normalizeNarrativeText(result.why_fix_works) || "Applied standard reliability improvements."}
          </p>
        </div>
      )}

      {visibleSections.opt && result.optimized_code && result.optimized_code !== result.fix && (
        <div className="animate-in fade-in slide-in-from-bottom-2 duration-500 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-xl p-6 shadow-sm">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-200 mb-4">Optimization</h3>
          <div className="relative group bg-gray-50 dark:bg-gray-950 border border-gray-200 dark:border-gray-800 rounded-lg">
            <CopyButton text={result.optimized_code} section="opt" />
            <div className="p-4 overflow-x-auto">
              <pre className="text-sm font-mono text-gray-900 dark:text-gray-200 whitespace-pre-wrap break-words pr-8">{safeClean(result.optimized_code)}</pre>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
